// Expanded paint list - copy this into the seedPaintDatabase function

export const expandedPaintList = [
  // ===== CITADEL PAINTS =====

  // BASE PAINTS (23 colors)
  { brand: 'Citadel', name: 'Abaddon Black', hexColor: '#000000', type: 'base' },
  { brand: 'Citadel', name: 'Corax White', hexColor: '#FFFFFF', type: 'base' },
  { brand: 'Citadel', name: 'Celestra Grey', hexColor: '#90A8A4', type: 'base' },
  { brand: 'Citadel', name: 'Death Guard Green', hexColor: '#556229', type: 'base' },
  { brand: 'Citadel', name: 'Deathworld Forest', hexColor: '#5C6730', type: 'base' },
  { brand: 'Citadel', name: 'Incubi Darkness', hexColor: '#0B474A', type: 'base' },
  { brand: 'Citadel', name: 'Caliban Green', hexColor: '#00401F', type: 'base' },
  { brand: 'Citadel', name: 'Waaagh! Flesh', hexColor: '#1A5E3C', type: 'base' },
  { brand: 'Citadel', name: 'Castellan Green', hexColor: '#264715', type: 'base' },
  { brand: 'Citadel', name: 'Nocturne Green', hexColor: '#1C331E', type: 'base' },
  { brand: 'Citadel', name: 'Kantor Blue', hexColor: '#02134E', type: 'base' },
  { brand: 'Citadel', name: 'Macragge Blue', hexColor: '#0F3D7C', type: 'base' },
  { brand: 'Citadel', name: 'Thousand Sons Blue', hexColor: '#005B7C', type: 'base' },
  { brand: 'Citadel', name: 'Naggaroth Night', hexColor: '#3F286E', type: 'base' },
  { brand: 'Citadel', name: 'Daemonette Hide', hexColor: '#696684', type: 'base' },
  { brand: 'Citadel', name: 'Screamer Pink', hexColor: '#7C1645', type: 'base' },
  { brand: 'Citadel', name: 'Khorne Red', hexColor: '#6A0001', type: 'base' },
  { brand: 'Citadel', name: 'Mephiston Red', hexColor: '#9C1E1E', type: 'base' },
  { brand: 'Citadel', name: 'Jokaero Orange', hexColor: '#EE3A08', type: 'base' },
  { brand: 'Citadel', name: 'Averland Sunset', hexColor: '#FDB825', type: 'base' },
  { brand: 'Citadel', name: 'Rhinox Hide', hexColor: '#5C3726', type: 'base' },
  { brand: 'Citadel', name: 'Mournfang Brown', hexColor: '#6A4F3B', type: 'base' },
  { brand: 'Citadel', name: 'Zandri Dust', hexColor: '#9E915C', type: 'base' },
  { brand: 'Citadel', name: 'Mechanicus Standard Grey', hexColor: '#3D4B4D', type: 'base' },
  { brand: 'Citadel', name: 'Rakarth Flesh', hexColor: '#A7A297', type: 'base' },

  // ===== ARMY PAINTER PAINTS =====

  // WARPAINTS (100+ colors available - here are the most popular)
  { brand: 'Army Painter', name: 'Matt Black', hexColor: '#000000', type: 'base' },
  { brand: 'Army Painter', name: 'Matt White', hexColor: '#FFFFFF', type: 'base' },
  { brand: 'Army Painter', name: 'Pure Red', hexColor: '#A92121', type: 'base' },
  { brand: 'Army Painter', name: 'Dragon Red', hexColor: '#C1272D', type: 'layer' },
  { brand: 'Army Painter', name: 'Lava Orange', hexColor: '#FF6A00', type: 'layer' },
  { brand: 'Army Painter', name: 'Daemonic Yellow', hexColor: '#FFD300', type: 'layer' },
  { brand: 'Army Painter', name: 'Greenskin', hexColor: '#6E8F47', type: 'base' },
  { brand: 'Army Painter', name: 'Angel Green', hexColor: '#42BA8A', type: 'layer' },
  { brand: 'Army Painter', name: 'Mutant Hue', hexColor: '#94E864', type: 'layer' },
  { brand: 'Army Painter', name: 'Ultramarine Blue', hexColor: '#0F4F8F', type: 'base' },
  { brand: 'Army Painter', name: 'Electric Blue', hexColor: '#41C9FF', type: 'layer' },
  { brand: 'Army Painter', name: 'Deep Blue', hexColor: '#232750', type: 'base' },
  { brand: 'Army Painter', name: 'Alien Purple', hexColor: '#5E1958', type: 'base' },
  { brand: 'Army Painter', name: 'Babe Blonde', hexColor: '#FFE4AE', type: 'layer' },
  { brand: 'Army Painter', name: 'Oak Brown', hexColor: '#6C3F10', type: 'base' },
  { brand: 'Army Painter', name: 'Leather Brown', hexColor: '#4B3A2A', type: 'base' },
  { brand: 'Army Painter', name: 'Desert Yellow', hexColor: '#CEB072', type: 'base' },
  { brand: 'Army Painter', name: 'Dirt Spatter', hexColor: '#7E5E3C', type: 'base' },
  { brand: 'Army Painter', name: 'Barbarian Flesh', hexColor: '#D1956F', type: 'base' },
  { brand: 'Army Painter', name: 'Tanned Flesh', hexColor: '#BE6C52', type: 'layer' },
  { brand: 'Army Painter', name: 'Elf Green', hexColor: '#007F4F', type: 'base' },
  { brand: 'Army Painter', name: 'Goblin Green', hexColor: '#438317', type: 'base' },
  { brand: 'Army Painter', name: 'Drake Tooth', hexColor: '#AF8E59', type: 'layer' },
  { brand: 'Army Painter', name: 'Kobold Skin', hexColor: '#BE704E', type: 'layer' },
  { brand: 'Army Painter', name: 'Gun Metal', hexColor: '#585B62', type: 'metallic' },
  { brand: 'Army Painter', name: 'Plate Mail Metal', hexColor: '#9DA5AA', type: 'metallic' },
  { brand: 'Army Painter', name: 'Shining Silver', hexColor: '#C3C8CE', type: 'metallic' },
  { brand: 'Army Painter', name: 'Greedy Gold', hexColor: '#CDA03A', type: 'metallic' },
  { brand: 'Army Painter', name: 'Weapon Bronze', hexColor: '#9F7A56', type: 'metallic' },
  { brand: 'Army Painter', name: 'Bright Gold', hexColor: '#F5E053', type: 'metallic' },

  // QUICKSHADES (Washes/Inks)
  { brand: 'Army Painter', name: 'Dark Tone Ink', hexColor: '#1C1410', type: 'shade' },
  { brand: 'Army Painter', name: 'Strong Tone Ink', hexColor: '#2F231A', type: 'shade' },
  { brand: 'Army Painter', name: 'Soft Tone Ink', hexColor: '#B89969', type: 'shade' },
  { brand: 'Army Painter', name: 'Light Tone Ink', hexColor: '#D5BB7D', type: 'shade' },
  { brand: 'Army Painter', name: 'Red Tone Ink', hexColor: '#8F1A1D', type: 'shade' },
  { brand: 'Army Painter', name: 'Green Tone Ink', hexColor: '#2D3C23', type: 'shade' },
  { brand: 'Army Painter', name: 'Blue Tone Ink', hexColor: '#1F2B46', type: 'shade' },
  { brand: 'Army Painter', name: 'Purple Tone Ink', hexColor: '#3D2245', type: 'shade' },

  // SPEEDPAINTS (Similar to Contrast)
  { brand: 'Army Painter', name: 'Grim Black', hexColor: '#141414', type: 'contrast' },
  { brand: 'Army Painter', name: 'Pallid Bone', hexColor: '#C5B89A', type: 'contrast' },
  { brand: 'Army Painter', name: 'Holy White', hexColor: '#E8E4DC', type: 'contrast' },
  { brand: 'Army Painter', name: 'Blood Red', hexColor: '#991E1E', type: 'contrast' },
  { brand: 'Army Painter', name: 'Zealot Yellow', hexColor: '#E5B200', type: 'contrast' },
  { brand: 'Army Painter', name: 'Orc Skin', hexColor: '#4F7335', type: 'contrast' },
  { brand: 'Army Painter', name: 'Highlord Blue', hexColor: '#2654A3', type: 'contrast' },
  { brand: 'Army Painter', name: 'Coven Purple', hexColor: '#663A6E', type: 'contrast' },
  { brand: 'Army Painter', name: 'Runic Grey', hexColor: '#667380', type: 'contrast' },
  { brand: 'Army Painter', name: 'Elemental Bolt', hexColor: '#00B3E5', type: 'contrast' },
];
